entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: smooth.criminal5698@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
api:
  dashboard: true
  debug: false

log:
  level: INFO

accessLog: {}

providers:
  docker:
    swarmMode: true
    exposedByDefault: false
    network: traefik