apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: exam
  labels:
    app: backend
    component: config
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: etudiants
  DB_USER: postgres
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/etudiants"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"