apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-pdb
  namespace: exam
spec:
  minAvailable: 1    # At least 1 database pod must be available
  selector:
    matchLabels:
      app: postgres