apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: exam
spec:
  minAvailable: 1    # At least 1 pod must be available
  selector:
    matchLabels:
      app: frontend