apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: exam-role
  namespace: exam
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]