apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: exam
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP